[package]
name = "kinet-execution-state-read"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
kinet-crypto = { workspace = true }
kinet-eth-types = { workspace = true }
kinet-tfm = { workspace = true }
kinet-types = { workspace = true }
kinet-validator = { workspace = true }

alloy-consensus = { workspace = true, features = ["k256"] }
alloy-primitives = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }

[dev-dependencies]
kinet-multi-sig = { workspace = true }
