[package]
name = "kinet-consensus-state"
version = "0.1.0"
edition = "2021"

# this is necessary for criterion bench options
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[dependencies]
kinet-blocktree = { workspace = true }
kinet-chain-config = { workspace = true }
kinet-consensus = { workspace = true }
kinet-consensus-types = { workspace = true }
kinet-crypto = { workspace = true }
kinet-eth-types = { workspace = true }
kinet-execution-state-read = { workspace = true }
kinet-types = { workspace = true }
kinet-validator = { workspace = true }

itertools = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
kinet-eth-block-policy = { workspace = true }
kinet-eth-block-validator = { workspace = true }
kinet-multi-sig = { workspace = true }
kinet-testutil = { workspace = true }

alloy-consensus = { workspace = true }
test-case = { workspace = true }
